### ISSUE TITLE
OSX: generates assembly code when no option

### ISSUE THREAD

**Issue by jowasp** [zscproject/OWASP-ZSC#83]
Steps to reproduce:
Choose zsc>shellcode>generate>osx_x86>system>command_to_execute
Set command to 'clear'
choose none as encoder type

```
Output assembly code?(y or n)> n
[+] Generated shellcode is:

\x68\x90\x90\x90\x72\x59\xc1\xe9\x10\xc1\xe9\x08\x51\x68\x63\x6c\x65\x61\x89\xe1\x68\x90\x90\x2d\x63\x5a\xc1\xea\x10\x52\x89\xe2\x68\x90\x2f\x73\x68\x5b\xc1\xeb\x08\x53\x68\x2f\x62\x69\x6e\x89\xe3\x31\xc0\x50\x51\x52\x53\x89\xe1\x31\xd2\x52\x51\x53\xb0\x3b\x6a\x2a\xcd\x80\xb0\x01\xb3\x01\xcd\x80
```

Issue: forgets to ask 'output shellcode too?(y or n)
Instead the shellcode is generate at once without requesting

**Comment by Ali-Razmjoo** [comment]
Hi johanna,
users are following this steps because of 2things
1- shellcodes
2-assembly code
if they  answer `yes` to assembly code, software will ask them if they want shellcode too, but if they don't want asm code, it will generate shellcode automaticly, because if they answer `no` to shellcode too, it will return nothing, [there is also a question for file output]
is it better to generate automaticly or ask if user want ? I think must of users want shellcode to use as payload in exploit, and shellcode c output it's just for testing if it's works, and it's better if we don't ask much questions, if it's need to be add , i can add it.

**Comment by CodeMaxx** [comment]
I agree with @Ali-Razmjoo . If the user doesn't want to see the assembly, he must have used the tool to get shellcode, so there is no need for asking.

**Comment by Ali-Razmjoo** [comment]
Because it's a ux thing, maybe we could ask more users about it, @Pratik151 @paraschetal , what's your ideas ?

**Comment by paraschetal** [comment]
I also think that shellcode should be output without asking the user, since it will be directly copy pasted by the user into an exploit. For assembly code and .c file we can ask.

**Comment by jowasp** [comment]
Either way is not a big issue , more of a UX thing. I think w can close this one ;-)

**Comment by Ali-Razmjoo** [comment]
thanks Johanna @jowasp  for notice about that by the way.
